FROM ubuntu:14.04
MAINTAINER Christoph Lukas <christoph.lukas@gmx.net>

ADD . /bd_build

RUN /bd_build/prepare.sh && \
	/bd_build/system_services.sh && \
	/bd_build/utilities.sh && \
	/bd_build/cleanup.sh

CMD ["/sbin/my_init"]
